name: Reliable Multicast Build
run-name: ${{github.actor}} building Reliable Multicast
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build ${{github.event_name}} event."
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: ./rmc

      - name: Run build process with repo
        uses: addnab/docker-run-action@v3
        with:
          image: magnusfeuer/reliable-multicast-build:latest
          options: |
            -v ${{github.workspace}}/docker-build/scripts:/scripts \
            -v ${{github.workspace}}/rmc:/src 
          run: |
            build
