name: Reliable Multicast Build
run-name: ${{github.actor}} building Reliable Multicast
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: ./rmc

      - name: Run build process with repo
        uses: addnab/docker-run-action@v3
        with:
          image: magnusfeuer/reliable-multicast-build:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          options: -v ${{github.workspace}}:/src
          run: |
            cd /src/rmc
            ls -lRa
            make debian
            ls -lR
